services:
  app:
    build: .
    container_name: TA-consultas-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app/uploads:/app/uploads
    networks:
      - ta_tunn_net
      - ta_internal_net

  db:
    image: postgres:17
    container_name: TA-consultas-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ta_internal_net

networks:
  ta_tunn_net:
    name: TA_tunn_net
    external: true
  ta_internal_net:
    name: TA_internal_net
    external: true
